version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5420:5432"
    environment:
      - POSTGRES_DB=cep
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - MAX_CONNECTIONS=300